name: Chromatic Storybook

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Instalar dependências
        run: yarn install --frozen-lockfile
      - name: Publicar Storybook no Chromatic
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: yarn workspace shared-ui chromatic --project-token=$CHROMATIC_PROJECT_TOKEN
