name: Deploy Docker Images

on:
  push:
    branches: [main, feature/test-deploy]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Instalar dependências
        run: yarn install --frozen-lockfile
      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build e push Host
        run: |
          docker build -t ghcr.io/$REPO/host:latest -f ./host/Dockerfile .
          docker push ghcr.io/$REPO/host:latest
      # (Deploy do shared-ui via Docker removido, pois deploy é feito via Chromatic/Storybook)
